### ISSUE TITLE
Suggestions and Typo Fix

### ISSUE THREAD

**Issue by MikoLone** [emmasax/json-formatter#4]
In the readme, you have this as the options object

{
      collapse: false, // Setting to 'true' this will format the JSON into a collapsable/expandable tree
      append_to: 'body', // A string of the id, class or element name to append the formatted json
      list_id: 'json' // The name of the id at the root ul of the formatted JSON
    }

append_to should be appendTo

It also isn't clear that when you say 

JSONFormatter.format(json, {});

that json is a javascript object and not a JSON string. Initially, I did this after reading the readme.

var myObj = {"blah":"blah"};
var json = JSON.stringify(myObj);
JSONFormatter.format(json, {});

and of course that didn't work. 

The other thing that might be nice is if the formatter would just return a DOM node of what you have produced.

Then I could put it wherever I want.

IE.  

var node = JSONFormatter.format(json, {});
myElement.appendChild(node);

**Comment by emmasax** [comment]
Thanks for the comments - feel free to send me a pull request with any changes you want to make.
